<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AbleKit\AbleKit.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Fixtures\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
